import fs from 'fs';
import { parse } from 'csv-parse/sync';

const files = [
  'data/SS_Architecture_Consolodation_Streams_Drops-with_Dependencies.csv.csv',
  'data/Unauthenticated_Tracking_Order_Number_(Backend_All_Files 2 _Streams_Drops-with_Dependencies.csv.csv'
];

const COLORS = ['cyan', 'teal', 'indigo', 'purple', 'blue', 'violet'];

function hashString(s) {
  let hash = 0;
  for (let i = 0; i < s.length; i++) hash = Math.imul(31, hash) + s.charCodeAt(i) | 0;
  return Math.abs(hash);
}

const streamsMap = new Map();

for (const file of files) {
  if (!fs.existsSync(file)) {
    console.warn("File not found, skipping:", file);
    continue;
  }
  const content = fs.readFileSync(file, 'utf8');
  const records = parse(content, { columns: true, skip_empty_lines: true });

  for (const r of records) {
    const streamId = r.workstream_hash;
    if (!streamsMap.has(streamId)) {
      const color = COLORS[hashString(streamId) % COLORS.length];
      const initials = (r.workstream_title || '').split(' ').map(w => w[0]).join('').substring(0, 4).toUpperCase();
      
      streamsMap.set(streamId, {
        workstream_id: streamId.substring(0, 8),
        id: streamId.substring(0, 8),
        title: r.workstream_title,
        description: r.workstream_description,
        initials,
        colorKey: color,
        priority: r.workstream_priority,
        complexity: parseInt(r.workstream_complexity, 10) || 5,
        estimated_completion_time: parseInt(r.estimated_completion_time, 10) || 2,
        workstream_hash: streamId,
        project: 'Unknown',
        drops: []
      });
    }

    const dependsOn = Array.from((r.dependencies || '').matchAll(/\b(\d+):/g)).map(m => m[1]);

    let tasks = [];
    try {
      const t = JSON.parse(r.tasks);
      tasks = Array.isArray(t) ? t : [r.tasks];
    } catch {
      tasks = [r.tasks];
    }
    
    if (tasks.length === 1 && !tasks[0]) tasks = [];

    const drop = {
      drop_id: r.drop_id,
      title: r.drop_title,
      tasks: tasks,
      priority: r.drop_priority,
      complexity: parseInt(r.drop_complexity, 10) || 4,
      status: r.drop_status,
      drop_hash: r.drop_hash,
      estimated_time: parseFloat(r.estimated_time) || 0,
      completion_time: parseFloat(r.completion_time) || 0,
      owner_id: r.owner_id || '',
      due_date: r.due_date,
      completion_date: r.completion_date,
      dependsOn: dependsOn,
    };

    streamsMap.get(streamId).drops.push(drop);
  }
}

const streamsList = Array.from(streamsMap.values());

// 1. Assign multiple owners fairly across drops to simulate realistic pipelines
const mockOwners = ['1', '2', '3', '4', '5'];
let dropCount = 0;
streamsList.forEach(s => {
  s.drops.forEach(d => {
    d.owner_id = mockOwners[dropCount % mockOwners.length];
    dropCount++;
  });
});

// 2. Inject artificial cross-stream dependencies to demonstrate Trace Links
if (streamsList.length > 1) {
  for (let i = 1; i < streamsList.length; i++) {
    const prevStream = streamsList[i-1];
    const currStream = streamsList[i];
    
    // First drop of current depends on last drop of previous
    if (prevStream.drops.length > 0 && currStream.drops.length > 0) {
      const parentDrop = prevStream.drops[prevStream.drops.length - 1];
      const childDrop = currStream.drops[0];
      
      if (!childDrop.dependsOn.includes(parentDrop.drop_id)) {
        childDrop.dependsOn.push(parentDrop.drop_id);
      }
    }
  }
}

const tsCode = `// ─────────────────────────────────────────────────────────────────────────────
// stagingData.ts — Real project data hydrated from staging CSV exports.
// DO NOT EDIT MANUALLY. Generated by scripts/ingest_csv.mjs.
// ─────────────────────────────────────────────────────────────────────────────

import { StreamColorKey } from './streams';

export interface StagingDrop {
  drop_id: string; title: string; tasks: string[]; priority: string;
  complexity: number; status: string; drop_hash: string;
  estimated_time: number; completion_time: number;
  owner_id: string; due_date: string; completion_date: string;
  dependsOn: string[];
}

export interface StagingStream {
  workstream_id: string; id: string; title: string; description: string;
  initials: string; colorKey: StreamColorKey; priority: string;
  complexity: number; estimated_completion_time: number;
  workstream_hash: string; project: string; drops: StagingDrop[];
}

export const STAGING_STREAMS: StagingStream[] = ${JSON.stringify(streamsList, null, 2)};

export const STAGING_DROPS = STAGING_STREAMS.flatMap(s => s.drops.map(d => ({ ...d, streamId: s.id })));

export function computeVelocityDelta(drops: StagingDrop[]): number {
  const completed = drops.filter(d => d.status === 'Completed' && d.completion_time > 0);
  if (completed.length === 0) return 0;
  const totalDelta = completed.reduce((acc, d) => acc + (d.estimated_time - d.completion_time), 0);
  return Math.round((totalDelta / completed.length) * 10);
}`;

fs.writeFileSync('src/lib/stagingData.ts', tsCode, 'utf8');

console.log('Successfully generated src/lib/stagingData.ts');
